# use artifactory for jar upload/download
# use multiple jobs
# use github.sha as a tag 
# use oidc role instead of secrets

name: app-ci

on:
  push:
    branches:
     - 'Feature/**'
    paths:
     - 'test/**'
     
permissions:
   id-token: write
   contents: read
   
jobs:

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checkout your respository
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: Install NPM Dependencies
        run: npm install
      

         
