
name: App-CI

on:
  push:
    branches:
     - 'Feature/**'
    paths:
     - 'test/**'
     
permissions:
   id-token: write
   contents: read
   
jobs:

  CI:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checkout your respository
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
    
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
      

         
